<script>
require(["jquery"], function($){
	fbq('track', 'ViewContent', {
	  content_name: 'Really Fast Running Shoes',
	  content_category: 'Apparel & Accessories > Shoes',
	  content_ids: ['1234'],
	  content_type: 'product',
	  value: 0.50,
	  currency: 'USD'
	 });
	$("body").on("click", ".tocart" function(){
		fbq("track", "addToCart", {
			content_type: 'product',
			currency: '<?= $block->getCurrentCurrencyCode() ?>'
		});
	});
});

</script>