<script>
require(["jquery"], function($){
	fbq('track', 'ViewContent', {
		content_category: '<?= $block->getCategoryName() ?>',
		content_type: 'product',
		content_name: '<?= $block->getProductName() ?>',
		content_ids: ['<?= $block->getProductSku() ?>'],
		currency: '<?= $block->getCurrentCurrencyCode() ?>',
		value: '<?= $block->getProductPrice() ?>',
	});
	$("body").on("click", ".tocart", function(){
		fbq("track", "addToCart", {
			content_type: 'product',
			currency: '<?= $block->getCurrentCurrencyCode() ?>',
			contents: [{"id": "<?= $block->getProductSku() ?>", "quantity": "1"}]
		});
	});
});
</script>